import type { ElementType, ElementDef } from '@/types/game'

export const ELEMENTS: Record<ElementType, ElementDef> = {
  fire: {
    name: 'Fire',
    color: '#FF4500',
    secondaryColor: '#FF8C00',
    particleColor: '#FFD700',
    description: 'Unleash blazing flames and scorching heat',
    abilities: [
      {
        name: 'Fireball',
        description: 'Launch a blazing fireball at enemies',
        cooldown: 1.5,
        damage: 25,
        range: 30,
        manaCost: 10,
        type: 'projectile',
        speed: 25,
        size: 0.35,
        hasTrail: true,
      },
      {
        name: 'Flame Burst',
        description: 'Explode in a ring of fire around you',
        cooldown: 5,
        damage: 35,
        range: 8,
        manaCost: 25,
        type: 'aoe',
        aoeRadius: 8,
      },
      {
        name: 'Fire Shield',
        description: 'Surround yourself with protective flames',
        cooldown: 12,
        damage: 0,
        range: 0,
        manaCost: 30,
        type: 'shield',
        shieldDuration: 5,
      },
    ],
  },
  water: {
    name: 'Water',
    color: '#1E90FF',
    secondaryColor: '#00BFFF',
    particleColor: '#87CEEB',
    description: 'Command the tides and heal your wounds',
    abilities: [
      {
        name: 'Water Blast',
        description: 'Shoot a pressurized water jet',
        cooldown: 1.5,
        damage: 20,
        range: 25,
        manaCost: 10,
        type: 'projectile',
        speed: 32,
        size: 0.4,
        hasArc: true,
      },
      {
        name: 'Wave Push',
        description: 'Send a wave crashing outward',
        cooldown: 5,
        damage: 30,
        range: 10,
        manaCost: 25,
        type: 'aoe',
        knockback: true,
      },
      {
        name: 'Healing Rain',
        description: 'Call down healing rain to restore health',
        cooldown: 10,
        damage: 0,
        range: 0,
        manaCost: 30,
        type: 'heal',
        healPerSecond: 18,
      },
    ],
  },
  ice: {
    name: 'Ice',
    color: '#00CED1',
    secondaryColor: '#E0FFFF',
    particleColor: '#B0E0E6',
    description: 'Freeze your foes and create icy barriers',
    abilities: [
      {
        name: 'Ice Spike',
        description: 'Hurl a piercing ice spike through enemies',
        cooldown: 1.5,
        damage: 22,
        range: 28,
        manaCost: 10,
        type: 'projectile',
        speed: 18,
        size: 0.3,
        piercing: true,
      },
      {
        name: 'Freeze Ray',
        description: 'Blast a cone of freezing cold that slows enemies',
        cooldown: 5,
        damage: 30,
        range: 10,
        manaCost: 25,
        type: 'aoe',
        slowDuration: 3,
      },
      {
        name: 'Ice Wall',
        description: 'Raise a wall of ice for protection',
        cooldown: 10,
        damage: 0,
        range: 0,
        manaCost: 30,
        type: 'shield',
        shieldDuration: 7,
      },
    ],
  },
  lightning: {
    name: 'Lightning',
    color: '#FFD700',
    secondaryColor: '#FFF8DC',
    particleColor: '#FFFF00',
    description: 'Strike with electric speed and power',
    abilities: [
      {
        name: 'Lightning Bolt',
        description: 'Zap enemies with a bolt of lightning',
        cooldown: 1.2,
        damage: 28,
        range: 35,
        manaCost: 10,
        type: 'projectile',
        speed: 50,
        size: 0.2,
      },
      {
        name: 'Chain Lightning',
        description: 'Lightning arcs between nearby enemies',
        cooldown: 6,
        damage: 20,
        range: 12,
        manaCost: 25,
        type: 'aoe',
        chainHits: 3,
      },
      {
        name: 'Speed Boost',
        description: 'Charge yourself with electric speed',
        cooldown: 10,
        damage: 0,
        range: 0,
        manaCost: 20,
        type: 'speed_boost',
        speedMultiplier: 2.5,
        boostDuration: 5,
      },
    ],
  },
  earth: {
    name: 'Earth',
    color: '#8B4513',
    secondaryColor: '#D2691E',
    particleColor: '#DEB887',
    description: 'Command stone and soil to crush enemies',
    abilities: [
      {
        name: 'Rock Throw',
        description: 'Hurl a massive boulder',
        cooldown: 2,
        damage: 35,
        range: 25,
        manaCost: 15,
        type: 'projectile',
        speed: 15,
        size: 0.6,
      },
      {
        name: 'Ground Slam',
        description: 'Slam the ground causing a shockwave',
        cooldown: 6,
        damage: 40,
        range: 8,
        manaCost: 30,
        type: 'aoe',
        aoeRadius: 5,
      },
      {
        name: 'Stone Armor',
        description: 'Coat yourself in protective stone',
        cooldown: 12,
        damage: 0,
        range: 0,
        manaCost: 30,
        type: 'shield',
        shieldDuration: 6,
      },
    ],
  },
  nature: {
    name: 'Nature',
    color: '#32CD32',
    secondaryColor: '#90EE90',
    particleColor: '#98FB98',
    description: 'Harness the power of plants and life',
    abilities: [
      {
        name: 'Vine Whip',
        description: 'Lash out with a thorny vine that heals on hit',
        cooldown: 1.5,
        damage: 20,
        range: 20,
        manaCost: 10,
        type: 'projectile',
        speed: 25,
        size: 0.3,
        onHitHeal: 5,
      },
      {
        name: 'Tree Summon',
        description: 'Summon spiked roots that heal you',
        cooldown: 6,
        damage: 30,
        range: 10,
        manaCost: 25,
        type: 'aoe',
        selfHealPercent: 25,
      },
      {
        name: 'Healing Aura',
        description: 'Surround yourself with restorative energy',
        cooldown: 10,
        damage: 0,
        range: 0,
        manaCost: 25,
        type: 'heal',
        healPerSecond: 20,
      },
    ],
  },
}
